# Generated by Django 5.0.2 on 2024-04-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='code2',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='code3',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='code4',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='1fe07bf24f5b', max_length=6),
        ),
    ]
