# Generated by Django 5.0.2 on 2024-04-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_customuser_firstname_customuser_lasttname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='lasttname',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='e2b266', max_length=6),
        ),
    ]
