# Generated by Django 5.0.2 on 2024-04-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_otp_code1_alter_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='88801b', max_length=6),
        ),
        migrations.AlterField(
            model_name='otp',
            name='exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
