# Generated by Django 5.0.2 on 2024-04-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kycverification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('id_type', models.CharField(choices=[('M', 'Passport'), ('F', 'National ID'), ('O', 'Driving License')], max_length=1)),
                ('id_proof', models.FileField(upload_to='id_proofs/')),
                ('selfie', models.FileField(upload_to='selfies/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='7d1cac', max_length=6),
        ),
    ]
