# Generated by Django 5.0.2 on 2024-04-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_kycverification_alter_otp_code1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='id_type',
            field=models.CharField(choices=[('Passport', 'Passport'), ('National ID', 'National ID'), ('Driving License', 'Driving License')], max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='9799b1', max_length=6),
        ),
    ]
