# Generated by Django 5.0.2 on 2024-04-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_coins_buyin_rate_coins_buying_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coins',
            name='buyin_rate',
        ),
        migrations.RemoveField(
            model_name='coins',
            name='selling_rate',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='ea9d00', max_length=6),
        ),
    ]
