# Generated by Django 5.0.2 on 2024-04-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_remove_coins_buyin_rate_remove_coins_selling_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_rate', models.IntegerField(blank=True, default=0)),
                ('selling_rate', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='7588a6', max_length=6),
        ),
    ]
