# Generated by Django 5.0.2 on 2024-04-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_setup_alter_otp_code1'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentmethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='pmethod/')),
                ('descripton', models.TextField(max_length=3000)),
                ('link', models.URLField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='e98a2a', max_length=6),
        ),
    ]
