# Generated by Django 5.0.2 on 2024-04-27 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_alter_otp_code1_alter_paymentmethod_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='f97ec9', max_length=6),
        ),
        migrations.CreateModel(
            name='buying_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('rate_naira', models.IntegerField(blank=True, default=0)),
                ('payment', models.IntegerField(blank=True, default=0)),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.coins')),
                ('paymentmethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.paymentmethod')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
