# Generated by Django 5.0.2 on 2024-04-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_alter_otp_code1_buying_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying_history',
            name='receiving_address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='1a875d', max_length=6),
        ),
    ]
