# Generated by Django 5.0.2 on 2024-05-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_buying_history_receiving_address_alter_otp_code1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying_history',
            name='payment',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='0e623a', max_length=6),
        ),
    ]
