# Generated by Django 5.0.2 on 2024-05-02 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_alter_buying_history_payment_alter_otp_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying_history',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coins',
            name='wallet_address',
            field=models.CharField(default='hhdudwddjq', max_length=500),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='845ce5', max_length=6),
        ),
        migrations.CreateModel(
            name='selling_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('rate_naira', models.IntegerField(blank=True, default=0)),
                ('payment', models.FloatField(blank=True, default=0.0)),
                ('payment_info', models.TextField(max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.coins')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
