# Generated by Django 5.0.2 on 2024-05-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_buying_history_status_coins_wallet_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='366627', max_length=6),
        ),
    ]
