# Generated by Django 5.0.2 on 2024-05-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0023_alter_otp_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling_history',
            name='sell_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='3649af', max_length=6),
        ),
    ]
