# Generated by Django 5.0.2 on 2024-05-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0024_selling_history_sell_date_alter_otp_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying_history',
            name='buy_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='4a7635', max_length=6),
        ),
    ]
