# Generated by Django 5.0.2 on 2024-05-04 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0025_buying_history_buy_date_alter_otp_code1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='buying_rate',
            new_name='crypto_buying_rate',
        ),
        migrations.RenameField(
            model_name='setup',
            old_name='selling_rate',
            new_name='crypto_selling_rate',
        ),
        migrations.AddField(
            model_name='setup',
            name='giftcard_buying_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='setup',
            name='giftcard_selling_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='buying_history',
            name='buy_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='d688f2', max_length=6),
        ),
        migrations.AlterField(
            model_name='selling_history',
            name='sell_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
