# Generated by Django 5.0.2 on 2024-05-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0027_giftcard_alter_otp_code1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='giftcard',
            new_name='giftcards',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='c5dfd9', max_length=6),
        ),
    ]
