# Generated by Django 5.0.2 on 2024-05-04 14:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0028_rename_giftcard_giftcards_alter_otp_code1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='e51392', max_length=6),
        ),
        migrations.CreateModel(
            name='giftcardbuying_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('rate_naira', models.IntegerField(blank=True, default=0)),
                ('recipient_name', models.CharField(blank=True, max_length=1000)),
                ('recipient_whatsapp', models.IntegerField(blank=True, default=0)),
                ('payment', models.FloatField(blank=True, default=0.0)),
                ('status', models.BooleanField(default=False)),
                ('buy_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('giftcard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.giftcards')),
                ('paymentmethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.paymentmethod')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
