# Generated by Django 5.0.2 on 2024-05-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0030_alter_otp_code1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='3f01dc', max_length=6),
        ),
    ]
