# Generated by Django 5.0.2 on 2024-05-06 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0031_alter_otp_code1'),
    ]

    operations = [
        migrations.CreateModel(
            name='uuid11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='5177ce', max_length=6),
        ),
    ]
