# Generated by Django 5.0.2 on 2024-05-06 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0033_uuid11_name_alter_otp_code1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='a2ec51', max_length=6),
        ),
        migrations.AlterField(
            model_name='uuid11',
            name='invoice',
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
    ]
