# Generated by Django 5.0.2 on 2024-05-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0034_alter_otp_code1_alter_uuid11_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='b068c8', max_length=6),
        ),
    ]
