# Generated by Django 5.0.2 on 2024-05-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0035_alter_otp_code1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uuid11',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='fceea3', max_length=6),
        ),
    ]
