# Generated by Django 5.0.2 on 2024-05-06 23:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0036_delete_uuid11_alter_otp_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying_history',
            name='invoice',
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='b54560', max_length=6),
        ),
    ]
