# Generated by Django 5.0.2 on 2024-05-06 23:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0037_buying_history_invoice_alter_otp_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardbuying_history',
            name='invoice',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='selling_history',
            name='invoice',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='buying_history',
            name='invoice',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='54e46a', max_length=6),
        ),
    ]
