# Generated by Django 5.0.2 on 2024-05-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0038_giftcardbuying_history_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='siteemail',
            field=models.CharField(default='Chiagoziewisdom060@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='3712f5', max_length=6),
        ),
    ]
