# Generated by Django 5.0.2 on 2024-05-10 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0039_setup_siteemail_alter_otp_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='date_summited',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='7e47be', max_length=6),
        ),
    ]
