# Generated by Django 5.0.2 on 2024-06-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0040_kycverification_date_summited_alter_otp_code1'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_plan', models.CharField(max_length=50)),
                ('network', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='e11778', max_length=6),
        ),
    ]
