# Generated by Django 5.0.2 on 2024-07-10 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0044_alter_otp_code1_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='8caada', max_length=6),
        ),
        migrations.CreateModel(
            name='balance_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.balance')),
            ],
        ),
    ]
