# Generated by Django 5.0.2 on 2024-07-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0045_alter_otp_code1_balance_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_history',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='34272c', max_length=6),
        ),
    ]
