# Generated by Django 5.0.2 on 2024-07-12 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0048_recent_activity_alter_otp_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent_activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='19e3b6', max_length=6),
        ),
    ]
