# Generated by Django 5.0.2 on 2024-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0049_recent_activity_user_alter_otp_code1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent_activity',
            name='date',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='776d1f', max_length=6),
        ),
    ]
