# Generated by Django 5.0.2 on 2024-07-12 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0050_remove_recent_activity_date_alter_otp_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent_activity',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='08f260', max_length=6),
        ),
    ]
