# Generated by Django 5.0.2 on 2024-07-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0051_recent_activity_date_alter_otp_code1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='005bfe', max_length=6),
        ),
    ]
