# Generated by Django 5.0.2 on 2024-07-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0052_alter_otp_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent_activity',
            name='a_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='deb22b', max_length=6),
        ),
    ]
