# Generated by Django 5.0.2 on 2024-07-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0055_remove_product_price_product_pro_id_alter_otp_code1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='airtime_p',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='airtime_p',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='22be74', max_length=6),
        ),
    ]
