# Generated by Django 5.0.2 on 2024-07-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0056_rename_product_airtime_p_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='airtime_p',
            new_name='Network',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='airtime_p',
            new_name='Network',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='1d2e1b', max_length=6),
        ),
    ]
