# Generated by Django 5.0.2 on 2024-07-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0059_remove_transaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='airtime_Transaction',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='2ce8eb', max_length=6),
        ),
    ]
