# Generated by Django 5.0.2 on 2024-07-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0061_balance_history_name_alter_otp_code1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtime_transaction',
            name='id',
        ),
        migrations.AddField(
            model_name='airtime_transaction',
            name='transaction_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='b48255', max_length=6),
        ),
    ]
