# Generated by Django 5.0.2 on 2024-07-21 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0062_remove_airtime_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtime_transaction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='airtime_transaction',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='balance_history',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='1799aa', max_length=6),
        ),
    ]
