# Generated by Django 5.0.2 on 2024-07-22 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0064_alter_otp_code1_dataplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataplan',
            name='Network',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='49a0bf', max_length=6),
        ),
        migrations.AddField(
            model_name='dataplan',
            name='Network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.network'),
            preserve_default=False,
        ),
    ]
