# Generated by Django 5.0.2 on 2024-07-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0066_alter_otp_code1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataplan',
            name='user',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='f72ce0', max_length=6),
        ),
    ]
