# Generated by Django 5.0.2 on 2024-07-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0067_remove_dataplan_user_alter_otp_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataplan',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='d604ce', max_length=6),
        ),
    ]
