# Generated by Django 5.0.2 on 2024-07-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0069_alter_otp_code1_datap_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='88088b', max_length=6),
        ),
    ]
