# Generated by Django 5.0.2 on 2024-08-01 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0070_alter_otp_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='datap_history',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='e32f26', max_length=6),
        ),
    ]
