# Generated by Django 5.0.2 on 2024-08-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0071_datap_history_date_alter_otp_code1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance_history',
            name='name',
        ),
        migrations.RemoveField(
            model_name='balance_history',
            name='proof',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='67b053', max_length=6),
        ),
    ]
