# Generated by Django 5.0.2 on 2024-08-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0072_remove_balance_history_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_history',
            name='payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='40ab1b', max_length=6),
        ),
    ]
