# Generated by Django 5.0.2 on 2024-08-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0073_balance_history_payment_alter_otp_code1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance_history',
            old_name='payment',
            new_name='payamount',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='531337', max_length=6),
        ),
    ]
