# Generated by Django 5.0.2 on 2024-08-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0075_alter_otp_code1_bankdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent_activity',
            name='img',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='fe26fa', max_length=6),
        ),
    ]
