# Generated by Django 5.0.2 on 2024-08-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0076_remove_recent_activity_img_alter_otp_code1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='account_number',
            new_name='bank_name',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='user',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='ff1da9', max_length=6),
        ),
    ]
