# Generated by Django 5.0.2 on 2024-08-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0077_rename_account_number_bankdetails_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='c51dad', max_length=6),
        ),
    ]
