# Generated by Django 5.0.2 on 2024-08-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0079_alter_otp_code1_withd_his'),
    ]

    operations = [
        migrations.AddField(
            model_name='withd_his',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='withd_his',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withd_his',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='12244d', max_length=6),
        ),
    ]
