# Generated by Django 5.0.2 on 2024-08-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0080_withd_his_amount_withd_his_name_withd_his_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bankcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='d6bcfc', max_length=6),
        ),
    ]
