# Generated by Django 5.0.2 on 2024-08-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0081_alter_bankdetails_bankcode_alter_otp_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='withd_his',
            name='account_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='e35498', max_length=6),
        ),
    ]
