# Generated by Django 5.0.2 on 2024-08-12 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0082_withd_his_account_number_alter_otp_code1'),
    ]

    operations = [
        migrations.AddField(
            model_name='withd_his',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code1',
            field=models.CharField(default='0a8bcd', max_length=6),
        ),
    ]
